#!/usr/bin/env python3
"""
Action Store
============
Persistent storage for the Action Execution Center.
Manages actions (tasks generated by recommendations) and action_events (audit trail).

Tables:
  - actions: trackable tasks with 7-state pipeline
  - action_events: execution ledger of all status changes and notes

Status flow: new → approved → in_progress → waiting → done
             (snoozed and dismissed are side states)
"""

import json
import uuid
import os
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

# Use db.py abstraction (Postgres when DATABASE_URL is set, SQLite fallback)
try:
    import db as _db
    DB_TYPE = _db.DB_TYPE
except ImportError:
    _db = None
    DB_TYPE = "sqlite"

import sqlite3 as _sqlite3

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data.db")

# Connection helpers (reuse data_store pattern)
_conn = None

def get_conn():
    if _db and _db.DB_TYPE == "postgres":
        return _db.get_conn()
    global _conn
    if _conn is None:
        _conn = _sqlite3.connect(DB_PATH, check_same_thread=False)
        _conn.row_factory = _sqlite3.Row
        _conn.execute("PRAGMA journal_mode=WAL")
    return _conn

def return_conn(conn):
    if _db and _db.DB_TYPE == "postgres":
        _db.return_conn(conn)
        return
    pass  # SQLite uses shared connection

# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS action_center_actions (
    id TEXT PRIMARY KEY,
    business_id TEXT NOT NULL DEFAULT 'default',
    source TEXT NOT NULL DEFAULT 'manual',
    source_id TEXT,
    recommendation_id TEXT,
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'new',
    action_type TEXT,
    entity_type TEXT,
    entity_id TEXT,
    entity_name TEXT,
    due_at TEXT,
    snoozed_until TEXT,
    completed_at TEXT,
    dismissed_at TEXT,
    notes TEXT,
    outcome TEXT,
    metadata_json TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS action_center_events (
    id TEXT PRIMARY KEY,
    action_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    from_status TEXT,
    to_status TEXT,
    note TEXT,
    outcome TEXT,
    metadata_json TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_aca_business_id ON action_center_actions(business_id);
CREATE INDEX IF NOT EXISTS idx_aca_status ON action_center_actions(status);
CREATE INDEX IF NOT EXISTS idx_aca_priority ON action_center_actions(priority);
CREATE INDEX IF NOT EXISTS idx_aca_source_id ON action_center_actions(source_id);
CREATE INDEX IF NOT EXISTS idx_ace_action_id ON action_center_events(action_id);
"""

VALID_STATUSES = {"new", "approved", "in_progress", "waiting", "snoozed", "done", "dismissed"}
VALID_PRIORITIES = {"high", "medium", "low"}
ACTIVE_STATUSES = {"new", "approved", "in_progress", "waiting"}
CLOSED_STATUSES = {"snoozed", "done", "dismissed"}

def init_db():
    """Initialize the actions schema."""
    conn = get_conn()
    conn.executescript(SCHEMA_SQL)
    conn.commit()
    return_conn(conn)

# ---------------------------------------------------------------------------
# CRUD
# ---------------------------------------------------------------------------

def _row_to_dict(row) -> Dict[str, Any]:
    """Convert a DB row to a dict."""
    if row is None:
        return None
    if isinstance(row, dict):
        d = dict(row)
    elif hasattr(row, "keys"):
        d = {k: row[k] for k in row.keys()}
    else:
        d = dict(row)
    # Parse metadata_json
    if d.get("metadata_json"):
        try:
            d["metadata"] = json.loads(d["metadata_json"])
        except (json.JSONDecodeError, TypeError):
            d["metadata"] = {}
    else:
        d["metadata"] = {}
    d.pop("metadata_json", None)
    return d

def get_actions(
    business_id: str = "default",
    status: Optional[str] = None,
    priority: Optional[str] = None,
    source: Optional[str] = None,
    include_closed: bool = False,
    limit: int = 100,
) -> Tuple[List[Dict], Dict[str, int]]:
    """Get actions with optional filters. Returns (actions, counts)."""
    conn = get_conn()
    
    where_clauses = ["business_id = ?"]
    params = [business_id]
    
    if status and status != "all":
        where_clauses.append("status = ?")
        params.append(status)
    elif not include_closed:
        # Exclude closed statuses unless explicitly included
        placeholders = ",".join(["?" for _ in ACTIVE_STATUSES])
        where_clauses.append(f"status IN ({placeholders})")
        params.extend(list(ACTIVE_STATUSES))
    
    if priority:
        where_clauses.append("priority = ?")
        params.append(priority)
    
    if source:
        where_clauses.append("source = ?")
        params.append(source)
    
    where_sql = " AND ".join(where_clauses)
    params.append(limit)
    
    rows = conn.execute(
        f"SELECT * FROM action_center_actions WHERE {where_sql} ORDER BY \
        CASE priority WHEN 'high' THEN 0 WHEN 'medium' THEN 1 WHEN 'low' THEN 2 ELSE 3 END, \
        created_at ASC LIMIT ?",
        params
    ).fetchall()
    
    actions = [_row_to_dict(r) for r in rows]
    
    # Get counts by status
    count_rows = conn.execute(
        "SELECT status, COUNT(*) as cnt FROM action_center_actions WHERE business_id = ? GROUP BY status",
        [business_id]
    ).fetchall()
    
    counts = {s: 0 for s in VALID_STATUSES}
    for cr in count_rows:
        s = cr["status"] if hasattr(cr, "__getitem__") else cr[0]
        c = cr["cnt"] if hasattr(cr, "__getitem__") else cr[1]
        counts[s] = c
    
    return_conn(conn)
    return actions, counts

def get_action(action_id: str) -> Optional[Dict]:
    """Get a single action by ID."""
    conn = get_conn()
    row = conn.execute("SELECT * FROM action_center_actions WHERE id = ?", [action_id]).fetchone()
    return_conn(conn)
    return _row_to_dict(row)

def get_action_events(action_id: str) -> List[Dict]:
    """Get all events for an action."""
    conn = get_conn()
    rows = conn.execute(
        "SELECT * FROM action_center_events WHERE action_id = ? ORDER BY created_at ASC",
        [action_id]
    ).fetchall()
    return_conn(conn)
    return [_row_to_dict(r) for r in rows]

def create_action(
    business_id: str = "default",
    source: str = "manual",
    source_id: Optional[str] = None,
    recommendation_id: Optional[str] = None,
    title: str = "",
    description: Optional[str] = None,
    priority: str = "medium",
    action_type: Optional[str] = None,
    entity_type: Optional[str] = None,
    entity_id: Optional[str] = None,
    entity_name: Optional[str] = None,
    due_at: Optional[str] = None,
    notes: Optional[str] = None,
    metadata: Optional[Dict] = None,
) -> Dict:
    """Create a new action."""
    action_id = str(uuid.uuid4())
    now = datetime.utcnow().isoformat()
    meta_json = json.dumps(metadata) if metadata else None
    
    conn = get_conn()
    conn.execute(
        """INSERT INTO action_center_actions (
            id, business_id, source, source_id, recommendation_id,
            title, description, priority, status,
            action_type, entity_type, entity_id, entity_name,
            due_at, notes, metadata_json, created_at, updated_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'new', ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        [action_id, business_id, source, source_id, recommendation_id,
         title, description, priority,
         action_type, entity_type, entity_id, entity_name,
         due_at, notes, meta_json, now, now]
    )
    
    # Create initial event
    event_id = str(uuid.uuid4())
    conn.execute(
        """INSERT INTO action_center_events (id, action_id, event_type, to_status, created_at)
        VALUES (?, ?, 'created', 'new', ?)""",
        [event_id, action_id, now]
    )
    
    conn.commit()
    return_conn(conn)
    return get_action(action_id)

def update_action(action_id: str, updates: Dict[str, Any]) -> Optional[Dict]:
    """Partially update an action. Returns updated action or None if not found."""
    existing = get_action(action_id)
    if not existing:
        return None
    
    allowed_fields = {
        "title", "description", "priority", "status",
        "action_type", "entity_type", "entity_id", "entity_name",
        "due_at", "snoozed_until", "completed_at", "dismissed_at",
        "notes", "outcome"
    }
    
    set_clauses = []
    params = []
    old_status = existing.get("status", "new")
    new_status = old_status
    
    for key, value in updates.items():
        if key not in allowed_fields:
            continue
        if key == "status":
            if value not in VALID_STATUSES:
                raise ValueError(f"Invalid status: {value}. Must be one of {VALID_STATUSES}")
            new_status = value
            # Set timestamp fields based on status
            now = datetime.utcnow().isoformat()
            if value == "done" and not updates.get("completed_at"):
                set_clauses.append("completed_at = ?")
                params.append(now)
            elif value == "dismissed" and not updates.get("dismissed_at"):
                set_clauses.append("dismissed_at = ?")
                params.append(now)
        set_clauses.append(f"{key} = ?")
        params.append(value)
    
    if not set_clauses:
        return existing
    
    now = datetime.utcnow().isoformat()
    set_clauses.append("updated_at = ?")
    params.append(now)
    params.append(action_id)
    
    conn = get_conn()
    conn.execute(
        f"UPDATE action_center_actions SET {', '.join(set_clauses)} WHERE id = ?",
        params
    )
    
    # Create status change event if status changed
    if new_status != old_status:
        event_id = str(uuid.uuid4())
        conn.execute(
            """INSERT INTO action_center_events (id, action_id, event_type, from_status, to_status, note, created_at)
            VALUES (?, ?, 'status_changed', ?, ?, ?, ?)""",
            [event_id, action_id, old_status, new_status,
             updates.get("notes", "") if updates.get("notes") else None, now]
        )
    
    conn.commit()
    return_conn(conn)
    return get_action(action_id)

def add_event(
    action_id: str,
    event_type: str,
    note: Optional[str] = None,
    outcome: Optional[str] = None,
    metadata: Optional[Dict] = None,
) -> Dict:
    """Add an event to an action's history."""
    event_id = str(uuid.uuid4())
    now = datetime.utcnow().isoformat()
    meta_json = json.dumps(metadata) if metadata else None
    
    conn = get_conn()
    conn.execute(
        """INSERT INTO action_center_events (id, action_id, event_type, note, outcome, metadata_json, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)""",
        [event_id, action_id, event_type, note, outcome, meta_json, now]
    )
    conn.commit()
    return_conn(conn)
    return {
        "id": event_id,
        "action_id": action_id,
        "event_type": event_type,
        "note": note,
        "outcome": outcome,
        "metadata": metadata or {},
        "created_at": now,
    }

# ---------------------------------------------------------------------------
# Demo Seeding
# ---------------------------------------------------------------------------

DEMO_ACTIONS = [
    {
        "source_id": "demo:revenue-below-target",
        "title": "Revenue below target: $5,213 of $85,000",
        "description": "Revenue is $79,787 below the monthly goal. Focus on closing pipeline opportunities and following up on stalled deals.",
        "priority": "high",
        "action_type": "revenue",
        "entity_type": "kpi",
        "entity_name": "Monthly Revenue",
    },
    {
        "source_id": "demo:stale-leads",
        "title": "Contact 3 stale lead(s)",
        "description": "You have leads that haven't been contacted in 7+ days. Reach out within 24 hours to maximize conversion rates.",
        "priority": "medium",
        "action_type": "follow_up",
        "entity_type": "leads",
        "entity_name": "Stale Leads",
    },
    {
        "source_id": "demo:stuck-opportunity",
        "title": "Follow up on stuck opportunity: [SAMPLE] Kitchen remodel - Patricia Johnson",
        "description": "This opportunity has been in the same stage for 21 days. Call the client to check on their decision timeline.",
        "priority": "high",
        "action_type": "follow_up",
        "entity_type": "opportunity",
        "entity_id": "demo-opp-001",
        "entity_name": "[SAMPLE] Patricia Johnson",
    },
    {
        "source_id": "demo:referral-opportunities",
        "title": "Leverage 6 referral opportunities",
        "description": "Existing satisfied clients can introduce you to new business. Reach out to top-value clients and ask for referrals.",
        "priority": "medium",
        "action_type": "outreach",
        "entity_type": "referrals",
        "entity_name": "Referral Pipeline",
    },
    {
        "source_id": "demo:training-followup",
        "title": "Complete Training: Lead Conversion Mastery",
        "description": "You haven't completed the Lead Conversion Mastery training module. This can help improve your 0% conversion rate.",
        "priority": "low",
        "action_type": "training",
        "entity_type": "training",
        "entity_name": "Lead Conversion Mastery",
    },
    {
        "source_id": "demo:cashflow-review",
        "title": "Review cash flow for upcoming payroll",
        "description": "With $5,213 in MTD revenue against $85K goal, review your cash position before the next payroll cycle.",
        "priority": "medium",
        "action_type": "financial",
        "entity_type": "finance",
        "entity_name": "Cash Flow",
    },
]

def seed_demo_actions(business_id: str = "roofing"):
    """Seed demo actions if none exist yet. Idempotent — won't overwrite existing."""
    conn = get_conn()
    
    # Check if any demo actions already exist
    existing = conn.execute(
        "SELECT COUNT(*) as cnt FROM action_center_actions WHERE business_id = ? AND source = 'demo'",
        [business_id]
    ).fetchone()
    count = existing["cnt"] if existing else 0
    
    if count > 0:
        return_conn(conn)
        return {"seeded": 0, "existing": count, "message": "Demo actions already exist"}
    
    now = datetime.utcnow().isoformat()
    seeded = 0
    
    for action in DEMO_ACTIONS:
        action_id = str(uuid.uuid4())
        source_id = action["source_id"]
        
        # Check if this specific source_id already exists (idempotent)
        existing_row = conn.execute(
            "SELECT id FROM action_center_actions WHERE business_id = ? AND source_id = ?",
            [business_id, source_id]
        ).fetchone()
        
        if existing_row:
            continue
        
        conn.execute(
            """INSERT INTO action_center_actions (
                id, business_id, source, source_id,
                title, description, priority, status,
                action_type, entity_type, entity_id, entity_name,
                created_at, updated_at
            ) VALUES (?, ?, 'demo', ?, ?, ?, ?, 'new', ?, ?, ?, ?, ?, ?)""",
            [action_id, business_id, source_id,
             action["title"], action["description"], action["priority"],
             action.get("action_type"), action.get("entity_type"),
             action.get("entity_id"), action.get("entity_name"),
             now, now]
        )
        
        # Create initial event
        event_id = str(uuid.uuid4())
        conn.execute(
            """INSERT INTO action_center_events (id, action_id, event_type, to_status, created_at)
            VALUES (?, ?, 'created', 'new', ?)""",
            [event_id, action_id, now]
        )
        seeded += 1
    
    conn.commit()
    return_conn(conn)
    return {"seeded": seeded, "existing": 0, "message": f"Seeded {seeded} demo actions"}

def has_actions(business_id: str = "default") -> bool:
    """Check if any actions exist for a business."""
    conn = get_conn()
    row = conn.execute(
        "SELECT COUNT(*) as cnt FROM action_center_actions WHERE business_id = ?",
        [business_id]
    ).fetchone()
    count = row["cnt"] if row else 0
    return_conn(conn)
    return count > 0
